---
abstract: 'automatically apply roles at object creation time'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::More: 0.96
  Test::Requires: 0
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.015, CPAN::Meta::Converter version 2.120921'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooX-Traits
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  MooX::Traits:
    file: lib/MooX/Traits.pm
    version: 0.001
recommends:
  Moo::Role: 0
requires:
  Module::Runtime: 0
  Role::Tiny: 1.000000
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/MooX-Traits/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=MooX-Traits
  homepage: https://metacpan.org/release/MooX-Traits
  license: http://dev.perl.org/licenses/
version: 0.001
